version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - banking-network

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - banking-network

  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - banking-network

  account-db:
    image: postgres:16.2-alpine
    container_name: account-db
    environment:
      POSTGRES_USER: account_user
      POSTGRES_PASSWORD: account_password
      POSTGRES_DB: account_db
    ports:
      - "5432:5432"
    networks:
      - banking-network

  transfer-db:
    image: postgres:16.2-alpine
    container_name: transfer-db
    environment:
      POSTGRES_USER: transfer_user
      POSTGRES_PASSWORD: transfer_password
      POSTGRES_DB: transfer_db
    ports:
      - "5433:5432"
    networks:
      - banking-network

  notification-db:
    image: postgres:16.2-alpine
    container_name: notification-db
    environment:
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: notification_password
      POSTGRES_DB: notification_db
    ports:
      - "5434:5432"
    networks:
      - banking-network

  zipkin:
    image: openzipkin/zipkin:3.0.4
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - banking-network

  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - banking-network

  grafana:
    image: grafana/grafana:10.3.3
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - banking-network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
      - ACCOUNT_SERVICE_URL=http://account-service:8081
      - TRANSFER_SERVICE_URL=http://transfer-service:8082
      - NOTIFICATION_SERVICE_URL=http://notification-service:8083
    depends_on:
      - redis
      - zipkin
    networks:
      - banking-network

  account-service:
    build:
      context: ./account-service
    container_name: account-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://account-db:5432/account_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - account-db
      - kafka
      - zipkin
    networks:
      - banking-network

  transfer-service:
    build:
      context: ./transfer-service
    container_name: transfer-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://transfer-db:5432/transfer_db
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - transfer-db
      - redis
      - kafka
      - zipkin
    networks:
      - banking-network

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notification-db:5432/notification_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - notification-db
      - kafka
      - zipkin
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge
