server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            redis-rate-limiter.requestedTokens: 1
      routes:
        - id: account-service
          uri: ${ACCOUNT_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/accounts/**
        - id: transfer-service
          uri: ${TRANSFER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/transfers/**
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/notifications/**

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
